Basic MLP Implementation

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# Initializing input array
X = np.array([[0.5, 0.8]])
X

array([[0.5, 0.8]])

In [ ]:
X.shape

(1, 2)

In [ ]:
# Initialize weights and biases for 2 inputs and 3 neurons respectively
W = np.array([[0.1,0.2, 0.3], [.4, .5, .6]])
W

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6]])

In [ ]:
W.shape

(2, 3)

In [ ]:
b = np.array([[0.01, 0.02, 0.03]])
b.shape

(1, 3)

In [ ]:
# Linear transformation → z = XW + b

Z = np.dot(X, W) + b
Z

array([[0.38, 0.52, 0.66]])

In [ ]:
print("Input X:\n", X)
print("\nWeights W:\n", W)
print("\nBias b:\n", b)
print("\nOutput (Z = XW + b):\n", Z)

Input X:
 [[0.5 0.8]]

Weights W:
 [[0.1 0.2 0.3]
 [0.4 0.5 0.6]]

Bias b:
 [[0.01 0.02 0.03]]

Output (Z = XW + b):
 [[0.38 0.52 0.66]]


#### Adding Activation Function

In [ ]:
#sigmoid activation function

def sigmoid(x):
  return 1 / (1 + np.exp(-x))

In [ ]:
A = sigmoid(Z)
A

array([[0.5938731 , 0.62714777, 0.65926039]])

### Understanding Forward Propagation



```
Input Layer        Hidden Layer              Output Layer
(2 neurons)        (4 neurons)               (1 neuron)

   x1  ● ─────┐      ● h1 ─────┐
              ├────▶ ● h2 ─────┼────▶ ● y
   x2  ● ─────┘      ● h3 ─────┘
                     ● h4

```

In [ ]:
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])

# X.shape = (4, 2)

# 4 rows → 4 training samples

# 2 columns → 2 input features = Number of Neurons in input layer

In [ ]:
# Initialize weights and biases
np.random.seed(1)
input_dim = 2 #X.shape[1]
hidden_dim = 4
output_dim = 1

In [ ]:
W1 = np.random.randn(input_dim, hidden_dim) # (2,4) = (rows, cols)
# Here, rand (2,4) provides 2*3 = 6 equally distributed values.
W1

array([[ 1.62434536, -0.61175641, -0.52817175, -1.07296862],
       [ 0.86540763, -2.3015387 ,  1.74481176, -0.7612069 ]])

In [ ]:
b1 = np.zeros((1, hidden_dim))
b1

array([[0., 0., 0., 0.]])

In [ ]:
W2 = np.random.randn(hidden_dim, output_dim)
b2 = np.zeros((1, output_dim))

In [ ]:
# Sigmoid activation
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [ ]:
# Forward Propagation
def forward_propagation(X, W1, b1, W2, b2):
  z1 = np.dot(X, W1) + b1
  A1 = sigmoid(z1)

  z2 = np.dot(A1, W2) + b2
  A2 = sigmoid(z2)
  return A2

In [ ]:
output = forward_propagation(X, W1, b1, W2, b2)

In [ ]:
print("Output from Forward Propagation:\n", output)

Output from Forward Propagation:
 [[0.43433595]
 [0.68796372]
 [0.54888958]
 [0.75509485]]
